export enum AuditActionType {
  ORDER_CREATED = 'ORDER_CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  DELIVERY_SCHEDULED = 'DELIVERY_SCHEDULED',
  DELIVERY_RESCHEDULED = 'DELIVERY_RESCHEDULED',
  DELIVERY_CONFIRMED = 'DELIVERY_CONFIRMED',
  TRANSPORT_CHANGED = 'TRANSPORT_CHANGED',
}
